### Softmax

##### array

In [1]:
import numpy as np

In [2]:
a = np.random.rand(5)
a

array([0.7505842 , 0.71376783, 0.33215352, 0.87514745, 0.22007971])

In [3]:
expa = np.exp(a)
expa

array([2.11823714, 2.04166944, 1.39396683, 2.39922905, 1.24617607])

In [4]:
soft_max = expa/sum(expa)
soft_max

array([0.23026122, 0.221938  , 0.15153002, 0.26080622, 0.13546454])

In [6]:
soft_max_sum = sum(soft_max)
soft_max_sum

0.9999999999999999

##### matrix

In [7]:
A = np.random.rand(100, 5)
expA = np.exp(A)

In [9]:
soft_max_A = expA/expA.sum(axis=1, keepdims=True)

In [11]:
soft_max_A_sum = soft_max_A.sum(axis=1)
soft_max_A_sum

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])