# Create model

In [21]:
import numpy as np
import pandas as pd

## Load pre-processed data

In [22]:
data_preprocessed = pd.read_csv('Absenteeism-data-preprocessed.csv')
# delete unnamed column
data_preprocessed = data_preprocessed.drop(['Unnamed: 0'], axis=1)
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## create targets

In [23]:
# assume median value for absent hours as normal, all what is more -> excesive
median = data_preprocessed['Absenteeism Time in Hours'].median()
print(median)

3.0


In [24]:
# assign 1 where absent time is greater than median, otherwise 0
targets = np.where(data_preprocessed['Absenteeism Time in Hours']> median, 1, 0) # targets -> np.array
print(targets)

[1 0 0 1 0 0 1 1 1 1 1 1 1 0 1 1 0 1 1 0 1 0 1 1 1 1 0 1 1 0 1 1 1 1 0 0 1
 1 1 1 0 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0
 1 1 0 1 0 0 0 0 1 1 1 1 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0 0 1 0
 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 0 0
 0 1 0 1 0 0 1 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 0 1 0 0 0 0
 0 0 1 0 0 1 1 0 0 1 0 1 1 1 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 0 1 0 0 1 0 0 1
 1 0 1 0 0 0 0 0 1 1 1 1 0 1 0 1 0 0 0 1 1 0 1 1 1 0 0 0 1 1 1 1 1 1 0 0 1
 0 1 0 1 0 1 0 0 0 0 0 1 1 0 1 0 0 0 1 1 0 1 0 1 0 0 1 1 1 0 0 0 0 0 1 1 1
 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0
 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0 1 0 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 0 0
 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0
 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 1 1 0 0 0 1
 0 1 1 1 1 1 1 1 1 1 0 1 

In [25]:
# load targets to original dataframe
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [26]:
# check data is balanced (shall be so, as we used median)
targets.sum()/ targets.shape[0] # devide sum of all by number of all items, shal be ca 50%

0.45571428571428574

In [27]:
# get rid of original hours column and store it in a new variable
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week',
                                            'Daily Work Load Average','Distance to Work'],axis=1)
data_with_targets is data_preprocessed # check these two are different objects

False

## select inputs for regression

In [28]:
data_with_targets.shape

(700, 15)

In [29]:
# select all but the excessive absentieesm
unsaceled_inputs = data_with_targets.iloc[:,:-1] # alternatively data_with_targets.iloc[:,0:14]
unsaceled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  
0               30          0         2     1  
1               31          0         1     0  
2               31          0         0     0  
3               24          0         2     0  
4               30          0         2     1

In [20]:
# standardize inputs
from sklearn.preprocessing import StandardScaler

In [ ]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [30]:
# select the columns to omit
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]
# prepare scaler
absenteeism_scaler = CustomScaler(columns_to_scale)
absenteeism_scaler.fit(unsaceled_inputs) # add standardizetion info, mean and SD for data set
# transform data
scaled_inputs = absenteeism_scaler.transform(unsaceled_inputs) # subtract mean and devide by SD
scaled_inputs.shape

C:\tools\Anaconda3\envs\py3-TF2.0\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\tools\Anaconda3\envs\py3-TF2.0\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  """


(700, 14)

## Split data for train and test, shuffle data

In [31]:
from sklearn.model_selection import train_test_split

In [36]:
# split
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state=20) 
# pseudo random shuffle with random_state

In [37]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(560, 14) (140, 14) (560,) (140,)


## Logistic regression with sklearn

In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [39]:
# define and fit regression model
reg = LogisticRegression()
reg.fit(x_train, y_train)

C:\tools\Anaconda3\envs\py3-TF2.0\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [40]:
# get regression accuracy
reg.score(x_train, y_train) # 78 percent estimated correctly

0.7839285714285714

## Manually check accuracy

In [43]:
model_outpust = reg.predict(x_train)
model_outpust

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [44]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [45]:
# compare predicted and given outputs
model_outpust == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [46]:
# calculate true values iver all values => accuracy
np.sum(model_outpust==y_train)/y_train.shape[0]

0.7839285714285714

## Intercept and coefficients

In [47]:
reg.intercept_

array([-0.21957576])

In [48]:
reg.coef_

array([[ 2.07452213,  0.33466331,  1.56097327,  1.32750188,  0.1878226 ,
        -0.07060017,  0.70649077, -0.03995965, -0.2009517 , -0.00462411,
         0.31937669, -0.13558227,  0.38168134, -0.33338757]])

In [51]:
feature_name = unsaceled_inputs.columns.values

In [54]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_) # traspose, as nd arrays are rows, but not columns
summary_table

Feature name  Coefficient
0                  Reason_1     2.074522
1                  Reason_2     0.334663
2                  Reason_3     1.560973
3                  Reason_4     1.327502
4               Month value     0.187823
5           Day of the week    -0.070600
6    Transportation Expense     0.706491
7          Distance to Work    -0.039960
8                       Age    -0.200952
9   Daily Work Load Average    -0.004624
10          Body Mass Index     0.319377
11                Education    -0.135582
12                 Children     0.381681
13                     Pets    -0.333388

In [55]:
# add intercept to the table
summary_table.index= summary_table.index +1 # shift all rows down by 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]] # add intercept row as first row
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.219576
1                  Reason_1     2.074522
2                  Reason_2     0.334663
3                  Reason_3     1.560973
4                  Reason_4     1.327502
5               Month value     0.187823
6           Day of the week    -0.070600
7    Transportation Expense     0.706491
8          Distance to Work    -0.039960
9                       Age    -0.200952
10  Daily Work Load Average    -0.004624
11          Body Mass Index     0.319377
12                Education    -0.135582
13                 Children     0.381681
14                     Pets    -0.333388

## Interpreting the coefficients

In [56]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient) #  'Odds ratio'shows the odds ratio of each feature
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
1                  Reason_1     2.074522    7.960741
3                  Reason_3     1.560973    4.763455
4                  Reason_4     1.327502    3.771610
7    Transportation Expense     0.706491    2.026866
13                 Children     0.381681    1.464745
2                  Reason_2     0.334663    1.397470
11          Body Mass Index     0.319377    1.376270
5               Month value     0.187823    1.206619
10  Daily Work Load Average    -0.004624    0.995387
8          Distance to Work    -0.039960    0.960828
6           Day of the week    -0.070600    0.931834
12                Education    -0.135582    0.873207
9                       Age    -0.200952    0.817952
0                 Intercept    -0.219576    0.802859
14                     Pets    -0.333388    0.716492

In [57]:
## Test model

In [58]:
reg.score(x_test,y_test)

0.7357142857142858

In [60]:
predicted_proba = reg.predict_proba(x_test) # probabilities
predicted_proba

array([[0.73825966, 0.26174034],
       [0.58795033, 0.41204967],
       [0.36712696, 0.63287304],
       [0.81162265, 0.18837735],
       [0.06127301, 0.93872699],
       [0.30690384, 0.69309616],
       [0.29493568, 0.70506432],
       [0.08079407, 0.91920593],
       [0.80400642, 0.19599358],
       [0.75999392, 0.24000608],
       [0.4622669 , 0.5377331 ],
       [0.15450706, 0.84549294],
       [0.04604734, 0.95395266],
       [0.72947484, 0.27052516],
       [0.23080142, 0.76919858],
       [0.55067175, 0.44932825],
       [0.52874769, 0.47125231],
       [0.55477826, 0.44522174],
       [0.38143834, 0.61856166],
       [0.0251927 , 0.9748073 ],
       [0.69578142, 0.30421858],
       [0.80421732, 0.19578268],
       [0.3768243 , 0.6231757 ],
       [0.39948746, 0.60051254],
       [0.18176149, 0.81823851],
       [0.75976147, 0.24023853],
       [0.46988997, 0.53011003],
       [0.88978022, 0.11021978],
       [0.13538822, 0.86461178],
       [0.79659382, 0.20340618],
       [0.

In [62]:
# select ONLY the probabilities referring to 1s
predicted_proba[:,1]

array([0.26174034, 0.41204967, 0.63287304, 0.18837735, 0.93872699,
       0.69309616, 0.70506432, 0.91920593, 0.19599358, 0.24000608,
       0.5377331 , 0.84549294, 0.95395266, 0.27052516, 0.76919858,
       0.44932825, 0.47125231, 0.44522174, 0.61856166, 0.9748073 ,
       0.30421858, 0.19578268, 0.6231757 , 0.60051254, 0.81823851,
       0.24023853, 0.53011003, 0.11021978, 0.86461178, 0.20340618,
       0.38508703, 0.70505605, 0.70183345, 0.56406796, 0.19578268,
       0.54314403, 0.20541739, 0.82126457, 0.44520741, 0.61158096,
       0.2094607 , 0.40337164, 0.21409118, 0.09894294, 0.842517  ,
       0.66696405, 0.71725297, 0.27020317, 0.20195465, 0.1710223 ,
       0.57388094, 0.08343439, 0.67981314, 0.28675297, 0.87278627,
       0.48596026, 0.93274693, 0.24666308, 0.08214027, 0.08284243,
       0.7284407 , 0.67005252, 0.3124804 , 0.86066991, 0.18419083,
       0.26006746, 0.01324125, 0.22067156, 0.81294039, 0.31498837,
       0.20469486, 0.07167719, 0.93340874, 0.4637118 , 0.65566

## Save the model

In [ ]:
import pickle
# pickle the model file
with open('model', 'wb') as file:
    pickle.dump(reg, file)
# pickle the scaler file
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)